"""Generate static catalogue pages, 10 articles each. No runtime backend required."""
from pathlib import Path
from html.parser import HTMLParser
from urllib.parse import urlsplit
import re,json,html,math,posixpath
from datetime import date
root=Path(__file__).resolve().parent.parent
size=10
class Article(HTMLParser):
 def __init__(self):super().__init__();self.h1=False;self.title=[];self.image=None;self.order=None
 def handle_starttag(self,t,attrs):
  a=dict(attrs)
  if t=='h1':self.h1=True
  if t=='article':self.order=a.get('data-article-order')
  if t=='img' and 'article-cover' in a.get('class','').split():self.image=a
 def handle_endtag(self,t):
  if t=='h1':self.h1=False
 def handle_data(self,d):
  if self.h1:self.title.append(d)
items=[]
for p in (root/'articles').glob('*.html'):
 s=p.read_text();a=Article();a.feed(s)
 m=re.search(r'<script type="application/ld\+json">(.*?)</script>',s,re.S)
 if not m:continue
 data=json.loads(m.group(1))
 if data.get('@type')!='BlogPosting':continue
 items.append((int(a.order) if a.order else 999999,p,a,data))
items.sort(key=lambda x:(x[0],x[1].name))
base_page=(root/'materials.html').read_text()
match=re.search(r'<link rel="canonical" href="([^"]+)"',base_page)
base=match.group(1).rsplit('/',1)[0] if match else None
page_count=max(1,math.ceil(len(items)/size))
def href(n):return 'materials.html' if n==1 else f'materials-{n}.html'
def card(item, number):
 _,p,a,d=item
 title=''.join(a.title).strip() or d.get('headline',d['name'])
 minutes=re.fullmatch(r'PT(\d+)M',d.get('timeRequired',''))
 meta_parts=[]
 published=d.get('datePublished')
 if published:
  day=date.fromisoformat(published[:10])
  months=['січня','лютого','березня','квітня','травня','червня','липня','серпня','вересня','жовтня','листопада','грудня']
  label=f'{day.day} {months[day.month-1]} {day.year}'
  meta_parts.append(f'<time datetime="{day.isoformat()}">{label}</time>')
 if minutes:meta_parts.append(f'Приблизно {minutes.group(1)} хв читання')
 meta='<div class="meta">'+' <span aria-hidden="true">·</span> '.join(meta_parts)+'</div>' if meta_parts else ''
 return f'<article class="article-card"><a class="card-link" href="articles/{p.name}"><span class="catalog-number" aria-label="Стаття {number}">{number:02d}</span><div class="catalog-copy">{meta}<h2>{html.escape(title)}</h2><p>{html.escape(d.get("description",""))}</p><span class="read-link">Читати статтю <span aria-hidden="true">↗</span></span></div></a></article>'
for n in range(1,page_count+1):
 nav=''
 if page_count>1:
  links=[]
  if n>1:links.append(f'<a href="{href(n-1)}" rel="prev">← Назад</a>')
  for i in range(1,page_count+1):
   links.append(f'<span aria-current="page" aria-label="Сторінка {i}">{i}</span>' if i==n else f'<a href="{href(i)}" aria-label="Сторінка {i}">{i}</a>')
  if n<page_count:links.append(f'<a href="{href(n+1)}" rel="next">Далі →</a>')
  nav='<nav class="catalog-pagination" aria-label="Сторінки матеріалів">'+''.join(links)+'</nav>'
 cards=''.join(card(item, number) for number,item in enumerate(items[(n-1)*size:n*size], start=(n-1)*size+1))
 main=f'<main id="main"><section class="catalog"><div class="page-heading"><span class="eyebrow">Зрозуміти більше</span><h1>Матеріали про OnlyFans і цифрову культуру</h1><p>Про платформу, людей і цифровий світ навколо нас.</p></div><div class="catalog-list">{cards}</div>{nav}</section></main>'
 s=re.sub(r'<main\b.*?</main>',lambda _:main,base_page,flags=re.S)
 suffix='' if n==1 else f' — сторінка {n}'
 title='Статті про OnlyFans'+suffix+' — Pixie Wixie'
 desc='Читайте матеріали Pixie Wixie про OnlyFans, підготовку до старту та цифрову культуру.'+(f' Сторінка {n}.' if n>1 else '')
 s=re.sub(r'<title>.*?</title>',lambda _:f'<title>{title}</title>',s)
 for field in ['name="description"','property="og:description"','name="twitter:description"']:
  s=re.sub(r'(<meta '+field+r' content=")[^"]*(">)',lambda m:m.group(1)+desc+m.group(2),s)
 for field in ['property="og:title"','name="twitter:title"']:
  s=re.sub(r'(<meta '+field+r' content=")[^"]*(">)',lambda m:m.group(1)+title+m.group(2),s)
 m=re.search(r'<script type="application/ld\+json">(.*?)</script>',s,re.S)
 data=json.loads(m.group(1));data.update(name=title,description=desc)
 if base:
  url=base+'/'+href(n);data['url']=url
  s=re.sub(r'(<link rel="canonical" href=")[^"]*(">)',lambda m:m.group(1)+url+m.group(2),s)
  s=re.sub(r'(<meta property="og:url" content=")[^"]*(">)',lambda m:m.group(1)+url+m.group(2),s)
 s=re.sub(r'<script type="application/ld\+json">.*?</script>',lambda _:'<script type="application/ld+json">'+json.dumps(data,ensure_ascii=False)+'</script>',s,flags=re.S)
 (root/href(n)).write_text(s)
# Only remove catalogue pages generated by this naming convention.
for p in root.glob('materials-*.html'):
 m=re.fullmatch(r'materials-(\d+)\.html',p.name)
 if m and int(m.group(1))>page_count:p.unlink()
print(f'Generated {page_count} catalogue page(s) for {len(items)} article(s), at most {size} per page.')
